import assert from "node:assert/strict";
import test from "node:test";
import { demoFamilyService, familyId, members } from "../lib/family";
import { DevelopmentAuthenticationProvider, DevelopmentIdentityProvider, IdentityService, NotConfiguredCameraIdentityProvider } from "../lib/identity";
import { checkPermission, permissionService } from "../lib/security/permissions";
import { auditService } from "../lib/security";

test("development identity verifies a known demo member", () => { const result = new DevelopmentIdentityProvider().verify({ requestId: "ID-1", familyId, claimedMemberId: members[0].id, method: "DEVELOPMENT", createdAt: "2026-09-20T00:00:00.000Z" }); assert.equal(result.status, "VERIFIED"); assert.equal(result.memberId, members[0].id); assert.equal(result.confidence, 1); });
test("unknown family or member is not verified", () => { const provider = new DevelopmentIdentityProvider(); assert.equal(provider.verify({ requestId: "ID-2", familyId: "UNKNOWN", claimedMemberId: "UNKNOWN", method: "DEVELOPMENT", createdAt: "2026-09-20T00:00:00.000Z" }).status, "NOT_VERIFIED"); });
test("identity sessions are active then revocable", () => { const service = new IdentityService(); const session = service.developmentSession(familyId, members[0].id, "OWNER"); assert.ok(session); assert.equal(service.getSession(session!.sessionId)?.status, "ACTIVE"); assert.equal(service.revokeSession(session!.sessionId)?.status, "REVOKED"); });
test("owner permissions are explicit", () => { const service = new IdentityService(); const session = service.developmentSession(familyId, members[0].id, "OWNER"); const result = permissionService.check(session, { actorId: members[0].id, actorType: "OWNER", familyId, memberId: members[0].id, permission: "HEALTH_PROFILE_VIEW", purpose: "PROFILE", timestamp: new Date().toISOString() }, "HEALTH_PROFILE_VIEW"); assert.equal(result.decision, "ALLOWED"); });
test("member isolation denies adult access to another member", () => { const service = new IdentityService(); const session = service.developmentSession(familyId, members[1].id, "ADULT_MEMBER"); const result = checkPermission(session, { actorId: members[1].id, actorType: "ADULT_MEMBER", familyId, memberId: members[0].id, permission: "MEMBER_VIEW", purpose: "PROFILE", timestamp: new Date().toISOString() }, "MEMBER_VIEW"); assert.equal(result.decision, "DENIED"); });
test("child and guest policies remain restricted", () => { const service = new IdentityService(); const child = service.developmentSession(familyId, members[1].id, "CHILD_MEMBER"); const guest = service.developmentSession(familyId, members[1].id, "GUEST"); assert.equal(permissionService.check(child, { actorId: members[1].id, actorType: "CHILD_MEMBER", familyId, permission: "MEMORY_CREATE", purpose: "MEMORY", timestamp: new Date().toISOString() }, "MEMORY_CREATE").decision, "DENIED"); assert.equal(permissionService.check(guest, { actorId: members[1].id, actorType: "GUEST", familyId, permission: "FAMILY_VIEW", purpose: "PROFILE", timestamp: new Date().toISOString() }, "FAMILY_VIEW").decision, "ALLOWED"); });
test("camera and authentication remain unconfigured/development only", () => { assert.equal(new NotConfiguredCameraIdentityProvider().captureIdentityInput().status, "NOT_CONFIGURED"); assert.equal(new DevelopmentAuthenticationProvider().authenticate().status, "DEVELOPMENT_ONLY"); });
test("audit records contain access metadata without health content", () => { const event = auditService.record({ actorId: members[0].id, familyId, memberId: members[0].id, action: "HEALTH_HISTORY_VIEW", resource: "PROFILE", allowed: true, reason: "test", timestamp: new Date().toISOString() }); assert.equal(JSON.stringify(event).includes("diabetes"), false); assert.equal(event.action, "HEALTH_HISTORY_VIEW"); });
test("family member lookup remains scoped", () => { assert.equal(Boolean(demoFamilyService.getMember(familyId, members[0].id)), true); assert.equal(demoFamilyService.getMember("UNKNOWN", members[0].id), undefined); });
