import assert from "node:assert/strict";
import test from "node:test";
import { DevelopmentNotificationProvider, InMemoryNotificationStore, NotificationManager, followUpNotification } from "../lib/notifications";
import { notificationScheduler } from "../lib/notifications";
import { demoFamilyService, familyId, members } from "../lib/family";
import { checkPermission } from "../lib/security/permissions";

test("development provider delivers only inside the app", () => { const result = new DevelopmentNotificationProvider().send({ id: "N-1", familyId, memberId: members[0].id, type: "SYSTEM", title: "Test", message: "Development notification", priority: "NORMAL", status: "PENDING", source: "SYSTEM", createdAt: new Date().toISOString() }); assert.equal(result.status, "DELIVERED"); assert.match(result.reason, /development interface/); });
test("notification lifecycle supports read, dismiss and cancel", () => { const manager = new NotificationManager(new InMemoryNotificationStore()); const item = manager.create({ familyId, memberId: members[0].id, type: "SYSTEM", title: "Test", message: "Test", priority: "NORMAL", source: "SYSTEM" }); assert.equal(manager.deliver(item.id, familyId, item.memberId)?.status, "DELIVERED"); assert.equal(manager.read(item.id, familyId, item.memberId)?.status, "READ"); assert.equal(manager.dismiss(item.id, familyId, item.memberId)?.status, "DISMISSED"); });
test("idempotency prevents duplicate follow-up notifications", () => { const manager = new NotificationManager(new InMemoryNotificationStore()); const followUp = { id: "FOLLOWUP-TEST", memberId: members[0].id, title: "Review", description: "Review", status: "OVERDUE" as const, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const first = manager.create(followUpNotification(familyId, followUp, true)); const second = manager.create(followUpNotification(familyId, followUp, true)); assert.equal(first.id, second.id); });
test("member notifications remain scoped", () => { const manager = new NotificationManager(new InMemoryNotificationStore()); manager.create({ familyId, memberId: members[0].id, type: "FAMILY", title: "Private", message: "Member A", priority: "NORMAL", source: "FAMILY" }); assert.equal(manager.list(familyId, members[1].id).length, 0); });
test("permission checks govern notification access", () => { const result = checkPermission({ memberId: members[0].id, familyId, role: "GUEST", verified: true }, { actorId: members[0].id, actorType: "GUEST", familyId, permission: "NOTIFICATION_VIEW", purpose: "SYSTEM", timestamp: new Date().toISOString() }, "NOTIFICATION_VIEW"); assert.equal(result.decision, "DENIED"); });
test("simulation notifications remain visibly simulation sourced", () => { const manager = new NotificationManager(new InMemoryNotificationStore()); const notification = manager.create({ familyId, type: "SIMULATION", title: "Simulation event", message: "Fictional simulation notification.", priority: "LOW", source: "SIMULATION" }); assert.equal(notification.source, "SIMULATION"); });
test("overdue follow-ups are classified without appointment claims", () => { const followUp = { id: "FOLLOWUP-OVERDUE-TEST", memberId: members[0].id, title: "Configured review", description: "Synthetic follow-up", status: "PENDING" as const, scheduledFor: "2020-01-01T00:00:00.000Z", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; demoFamilyService.saveFollowUp(followUp); const notifications = notificationScheduler.processOverdueFollowUps(new Date("2026-09-20T00:00:00.000Z")); assert.ok(notifications.some((item) => item.relatedFollowUpId === followUp.id)); assert.ok(notifications.every((item) => !item.message.includes("appointment"))); });
test("safety notification wording remains cautious", () => { const manager = new NotificationManager(new InMemoryNotificationStore()); const notification = manager.create({ familyId, type: "SAFETY", title: "Potential safety signal detected", message: "Review the AUTODOC assessment.", priority: "URGENT", source: "SAFETY_ENGINE" }); assert.equal(notification.priority, "URGENT"); assert.equal(notification.message.includes("emergency services"), false); assert.equal(notification.message.includes("diagnosed"), false); });
