import { NextResponse } from "next/server";
import { memoryService } from "@/lib/memory";
import { getDevelopmentAccess } from "@/lib/security";
type Context = { params: Promise<{ memberId: string }> };
const familyId = "FAMILY-DEMO-001";
export async function GET(_request: Request, context: Context) { const { memberId } = await context.params; const access = getDevelopmentAccess(familyId, memberId, "MEMORY_VIEW", "MEMORY"); if (!access.allowed) return NextResponse.json({ error: access.reason }, { status: 403 }); return NextResponse.json({ memories: memoryService.listMemberMemories(familyId, memberId), simulated: true }); }
export async function POST(request: Request, context: Context) { const { memberId } = await context.params; const access = getDevelopmentAccess(familyId, memberId, "MEMORY_CREATE", "MEMORY"); if (!access.allowed) return NextResponse.json({ error: access.reason }, { status: 403 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body || typeof body.key !== "string" || typeof body.value !== "string") return NextResponse.json({ error: "key and value are required" }, { status: 400 }); const memory = memoryService.createMemory({ familyId, memberId, key: body.key, value: body.value, category: "OTHER", source: "USER_PROVIDED", importance: "NORMAL", accessScope: "MEMBER" }); return NextResponse.json({ memory }, { status: 201 }); }
export async function PATCH(request: Request, context: Context) { const { memberId } = await context.params; const access = getDevelopmentAccess(familyId, memberId, "MEMORY_EDIT", "MEMORY"); if (!access.allowed) return NextResponse.json({ error: access.reason }, { status: 403 }); const body = await request.json().catch(() => null) as { id?: unknown; value?: unknown } | null; if (!body || typeof body.id !== "string" || typeof body.value !== "string") return NextResponse.json({ error: "id and value are required" }, { status: 400 }); const memory = memoryService.updateMemory(body.id, familyId, body.value, memberId); if (!memory) return NextResponse.json({ error: "Memory not found in member scope" }, { status: 404 }); return NextResponse.json({ memory }); }
export async function DELETE(request: Request, context: Context) { const { memberId } = await context.params; const access = getDevelopmentAccess(familyId, memberId, "MEMORY_DELETE", "MEMORY"); if (!access.allowed) return NextResponse.json({ error: access.reason }, { status: 403 }); const id = new URL(request.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "id is required" }, { status: 400 }); const deleted = memoryService.deleteMemory(id, familyId, memberId); return deleted ? NextResponse.json({ deleted: true }) : NextResponse.json({ error: "Memory not found in member scope" }, { status: 404 }); }
