import type { IdentityRole } from "@/lib/identity";
import type { Permission } from "./types";

const owner: Permission[] = ["FAMILY_VIEW", "FAMILY_EDIT", "MEMBER_VIEW", "MEMBER_EDIT", "HEALTH_PROFILE_VIEW", "HEALTH_PROFILE_EDIT", "HEALTH_HISTORY_VIEW", "HEALTH_HISTORY_EDIT", "MEMORY_VIEW", "MEMORY_CREATE", "MEMORY_EDIT", "MEMORY_DELETE", "FOLLOWUP_VIEW", "FOLLOWUP_CREATE", "FOLLOWUP_EDIT", "ASSESSMENT_VIEW", "ASSESSMENT_CREATE", "RESEARCH_VIEW", "RESEARCH_CREATE", "SIMULATION_VIEW", "SIMULATION_CREATE", "NOTIFICATION_VIEW", "NOTIFICATION_CREATE", "NOTIFICATION_MANAGE", "NOTIFICATION_SETTINGS_VIEW", "NOTIFICATION_SETTINGS_EDIT", "SYSTEM_SETTINGS_VIEW", "IDENTITY_MANAGE"];
const adult: Permission[] = ["FAMILY_VIEW", "MEMBER_VIEW", "HEALTH_PROFILE_VIEW", "HEALTH_HISTORY_VIEW", "MEMORY_VIEW", "MEMORY_CREATE", "MEMORY_EDIT", "FOLLOWUP_VIEW", "FOLLOWUP_CREATE", "ASSESSMENT_VIEW", "ASSESSMENT_CREATE", "RESEARCH_VIEW", "SIMULATION_VIEW"];
const child: Permission[] = ["FAMILY_VIEW", "MEMBER_VIEW", "MEMORY_VIEW", "ASSESSMENT_VIEW", "SIMULATION_VIEW"];
const guest: Permission[] = ["FAMILY_VIEW"];
export const permissionMatrix: Record<IdentityRole, Permission[]> = { OWNER: owner, ADMIN: owner, ADULT_MEMBER: adult, CHILD_MEMBER: child, GUEST: guest, SYSTEM: ["SYSTEM_SETTINGS_VIEW", "RESEARCH_VIEW", "SIMULATION_VIEW"] };
export function roleHasPermission(role: IdentityRole, permission: Permission) { return permissionMatrix[role].includes(permission); }
